FROM library/postgres:9.6.5

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD password

#CMD echo "start script"	

#ADD setup.sh /setup.sh
#RUN chmod 755 /setup.sh
#CMD SLEEP 30

EXPOSE 5432 5432
#CMD echo "WAIT 30 s"	
#CMD ["/bin/bash", "/setup.sh" , "localhost"]
