# Common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Rancher

jhipster:
    security:
        authentication:
            jwt:
                secret: 6c3a36bd48a2d9a8370fb53a63339a2bd697bf84
