version: '2'
services:
    transactionreceiver-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/transactionreceiver/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=transactionreceiver
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
